--truncate table dcalendar
--select * from DCALENDAR
--exec sp_cargaDCalendario

ALTER PROCEDURE SP_CARGADCALENDARIO
AS
BEGIN
	DECLARE @DATABASE AS DATETIME = '19000101', 
			@LINHA AS VARCHAR = NULL
--
	DECLARE	@DATAB AS DATETIME = NULL,
			@ANONUM AS BIGINT,
			@MESNUM AS BIGINT,
			@DIANUM AS BIGINT,
			@MESANONUM AS VARCHAR(50),
			@MESANOTXTABR AS VARCHAR(50),
			@MESANOTXTLON AS VARCHAR(50),
			@BIMESTRE AS VARCHAR(50),
			@TRIMESTRE AS VARCHAR(50),
			@DIASEMANANUM AS BIGINT,
			@DIASEMANATXTABR AS VARCHAR(3),
			@DIASEMANATXTLONG AS VARCHAR(50)

	SET NOCOUNT ON;
	SET LANGUAGE BRAZILIAN;

	WHILE (@DATABASE < = CONVERT(DATETIME, '31/12/2100', 103))
	BEGIN
		SET @DATAB = CONVERT(DATETIME, @DATABASE, 103) -- DD/MM/YYYY
		SET @ANONUM = DATEPART(YEAR, @DATAB)
		SET	@MESNUM = DATEPART(MONTH, @DATAB)
		SET	@DIANUM = DATEPART(DAY, @DATAB)
		SET @MESANONUM = CONVERT(VARCHAR, DATEPART(MONTH, @DATAB)) + '-' + CONVERT(VARCHAR, DATEPART(YEAR, @DATAB))
		SET @MESANOTXTABR = UPPER(CONVERT(VARCHAR(3), DATENAME(MONTH, @DATAB))) + '-' + CONVERT(VARCHAR, DATEPART(YEAR, @DATAB))
		SET	@MESANOTXTLON = UPPER(CONVERT(VARCHAR(50), DATENAME(MONTH, @DATAB))) + '-' + CONVERT(VARCHAR, DATEPART(YEAR, @DATAB))
		SET @BIMESTRE = NULL
		SET @BIMESTRE = CASE 
			WHEN DATEPART(MONTH, @DATABASE) IN (1, 2) THEN '1.BIMESTRE' --JAN E FEV
			WHEN DATEPART(MONTH, @DATABASE) IN (3, 4) THEN '2.BIMESTRE' --MAR E ABR
			WHEN DATEPART(MONTH, @DATABASE) IN (5, 6) THEN '3.BIMESTRE' --MAI E JUN
			WHEN DATEPART(MONTH, @DATABASE) IN (7, 8) THEN '4.BIMESTRE' --JUL E AGO
			WHEN DATEPART(MONTH, @DATABASE) IN (9, 10) THEN '5.BIMESTRE' --SET E OUT
			WHEN DATEPART(MONTH, @DATABASE) IN (11, 12) THEN '6.BIMESTRE' --NOV E DEZ
						END
		SET @BIMESTRE = @BIMESTRE + '.' + CONVERT(VARCHAR, @ANONUM)
		--
		SET @TRIMESTRE = NULL
		SET @TRIMESTRE = CASE 
			WHEN DATEPART(MONTH, @DATABASE) IN (1, 2, 3) THEN '1.TRIMESTRE' --JAN FEV, MAR
			WHEN DATEPART(MONTH, @DATABASE) IN (4, 5, 6) THEN '2.TRIMESTRE' --ABR, MAI, JUN
			WHEN DATEPART(MONTH, @DATABASE) IN (7, 8, 9) THEN '3.TRIMESTRE' --JUL, AGO, SET
			WHEN DATEPART(MONTH, @DATABASE) IN (10, 11, 12) THEN '4.TRIMESTRE' --OUT, NOV, DEZ
			END
		SET @TRIMESTRE = @TRIMESTRE + '.' + CONVERT(VARCHAR, @ANONUM)

		SET @DIASEMANANUM = DATEPART(WEEKDAY, @DATAB)
		SET @DIASEMANATXTABR = LEFT(UPPER(DATENAME(WEEKDAY,@DATAB)), 3)
		SET @DIASEMANATXTLONG = UPPER(DATENAME(WEEKDAY,@DATAB))
		SET @LINHA = CONVERT(DATETIME, @DATABASE, 103) -- DD/MM/YYYY
		-- 
		INSERT INTO DCALENDAR(DATAB, ANONUM, MESNUM, DIANUM, MESANONUM, MESANOTXTABR, MESANOTXTLON, BIMESTRE, TRIMESTRE, DIASEMANANUM, DIASEMANATXTABR, DIASEMANATXTLONG)
		VALUES (@DATAB, @ANONUM, @MESNUM, @DIANUM, @MESANONUM, @MESANOTXTABR, @MESANOTXTLON, @BIMESTRE, @TRIMESTRE, @DIASEMANANUM, @DIASEMANATXTABR, @DIASEMANATXTLONG) 
		SET @DATABASE = DATEADD(D, 1, @DATABASE)
	END 
	--
	PRINT 'ITS FINISH .....'
END
GO
