VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "cUF"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Attribute VB_Ext_KEY = "SavedWithClassBuilder6" ,"Yes"
Attribute VB_Ext_KEY = "Top_Level" ,"Yes"
Option Explicit
'local variable(s) to hold property value(s)
Private mvarIDUF As Double 'local copy
Private mvarNome As String 'local copy

Public Function ToList(pADODB As cADODB) As ADODB.Recordset
Dim strSQL As String
Dim oRSET As ADODB.Recordset

strSQL = "SELECT ID, NOME FROM UF ORDER BY NOME"
Set ToList = pADODB.OpenRSet(strSQL)
End Function

Public Property Let Nome(ByVal vData As String)
'used when assigning a value to the property, on the left side of an assignment.
'Syntax: X.Nome = 5
    mvarNome = vData
End Property


Public Property Get Nome() As String
'used when retrieving value of a property, on the right side of an assignment.
'Syntax: 'Debug.Print X.Nome
    Nome = mvarNome
End Property



Public Property Let IDUF(ByVal vData As Double)
'used when assigning a value to the property, on the left side of an assignment.
'Syntax: X.IDUF = 5
    mvarIDUF = vData
End Property


Public Property Get IDUF() As Double
'used when retrieving value of a property, on the right side of an assignment.
'Syntax: 'Debug.Print X.IDUF
    IDUF = mvarIDUF
End Property



